program RPCheffGarcomAPI;

{$R *.dres}

uses
  Vcl.Forms,
  Vcl.Themes,
  Vcl.Styles,
  GBWinService.Setup.Interfaces,
  APIRPCheff.View.Principal in 'Source\View\APIRPCheff.View.Principal.pas' {APIRPCheffViewPrincipal},
  APIRPCheff.Resources in 'Resources\APIRPCheff.Resources.pas',
  APIRPCheff.Controller.API in 'Source\Controller\APIRPCheff.Controller.API.pas',
  APIRPCheff.Entity.Error in 'Source\Model\Entity\APIRPCheff.Entity.Error.pas',
  APIRPCheff.Entity.Classes in 'Source\Model\Entity\APIRPCheff.Entity.Classes.pas',
  APIRPCheff.Components.Connection in 'Source\Model\Components\Conexao\APIRPCheff.Components.Connection.pas',
  APIRPCheff.Components in 'Source\Model\Components\APIRPCheff.Components.pas',
  APIRPCheff.Controller in 'Source\Controller\APIRPCheff.Controller.pas',
  APIRPCheff.Entity.Empresa in 'Source\Model\Entity\APIRPCheff.Entity.Empresa.pas',
  APIRPCheff.DAO.Base in 'Source\Model\DAO\APIRPCheff.DAO.Base.pas',
  APIRPCheff.DAO.Empresa in 'Source\Model\DAO\APIRPCheff.DAO.Empresa.pas',
  APIRPCheff.DAO.Factory in 'Source\Model\DAO\APIRPCheff.DAO.Factory.pas',
  APIRPCheff.Controller.Base in 'Source\Controller\APIRPCheff.Controller.Base.pas',
  APIRPCheff.Components.JSON in 'Source\Model\Components\JSON\APIRPCheff.Components.JSON.pas',
  APIRPCheff.Controller.Empresa in 'Source\Controller\APIRPCheff.Controller.Empresa.pas',
  APIRPCheff.Entity.Usuario in 'Source\Model\Entity\APIRPCheff.Entity.Usuario.pas',
  APIRPCheff.DAO.Usuario in 'Source\Model\DAO\APIRPCheff.DAO.Usuario.pas',
  APIRPCheff.Controller.Usuario in 'Source\Controller\APIRPCheff.Controller.Usuario.pas',
  APIRPCheff.Entity.Mesa in 'Source\Model\Entity\APIRPCheff.Entity.Mesa.pas',
  APIRPCheff.Entity.Types in 'Source\Model\Entity\APIRPCheff.Entity.Types.pas',
  APIRPCheff.DAO.Mesa in 'Source\Model\DAO\APIRPCheff.DAO.Mesa.pas',
  APIRPCheff.Controller.Mesa in 'Source\Controller\APIRPCheff.Controller.Mesa.pas',
  APIRPCheff.Entity.Categoria in 'Source\Model\Entity\APIRPCheff.Entity.Categoria.pas',
  APIRPCheff.DAO.Categoria in 'Source\Model\DAO\APIRPCheff.DAO.Categoria.pas',
  APIRPCheff.Controller.Categoria in 'Source\Controller\APIRPCheff.Controller.Categoria.pas',
  APIRPCheff.Entity.Produto in 'Source\Model\Entity\APIRPCheff.Entity.Produto.pas',
  APIRPCheff.Controller.Produto in 'Source\Controller\APIRPCheff.Controller.Produto.pas',
  APIRPCheff.DAO.Produto in 'Source\Model\DAO\APIRPCheff.DAO.Produto.pas',
  APIRPCheff.Entity.FormaPagamento in 'Source\Model\Entity\APIRPCheff.Entity.FormaPagamento.pas',
  APIRPCheff.DAO.FormaPagamento in 'Source\Model\DAO\APIRPCheff.DAO.FormaPagamento.pas',
  APIRPCheff.Controller.FormaPagamento in 'Source\Controller\APIRPCheff.Controller.FormaPagamento.pas',
  APIRPCheff.Entity.Opcional in 'Source\Model\Entity\APIRPCheff.Entity.Opcional.pas',
  APIRPCheff.DAO.Opcional in 'Source\Model\DAO\APIRPCheff.DAO.Opcional.pas',
  APIRPCheff.Entity.Venda in 'Source\Model\Entity\APIRPCheff.Entity.Venda.pas',
  APIRPCheff.DAO.Venda in 'Source\Model\DAO\APIRPCheff.DAO.Venda.pas',
  APIRPCheff.Controller.Venda in 'Source\Controller\APIRPCheff.Controller.Venda.pas',
  APIRPCheff.Entity.VendaItem in 'Source\Model\Entity\APIRPCheff.Entity.VendaItem.pas',
  APIRPCheff.DAO.VendaItem in 'Source\Model\DAO\APIRPCheff.DAO.VendaItem.pas',
  APIRPCheff.Entity.Caixa in 'Source\Model\Entity\APIRPCheff.Entity.Caixa.pas',
  APIRPCheff.DAO.Caixa in 'Source\Model\DAO\APIRPCheff.DAO.Caixa.pas',
  APIRPCheff.Service.Mesa.Abertura in 'Source\Model\Service\Mesa\Abertura\APIRPCheff.Service.Mesa.Abertura.pas',
  APIRPCheff.Service in 'Source\Model\Service\APIRPCheff.Service.pas',
  APIRPCheff.Entity.Promocao in 'Source\Model\Entity\APIRPCheff.Entity.Promocao.pas',
  APIRPCheff.DAO.Promocao in 'Source\Model\DAO\APIRPCheff.DAO.Promocao.pas',
  APIRPCheff.Service.Venda.LancarItem.Normal in 'Source\Model\Service\Venda\LancarItem\APIRPCheff.Service.Venda.LancarItem.Normal.pas',
  APIRPCheff.Entity.VendaItemOpcional in 'Source\Model\Entity\APIRPCheff.Entity.VendaItemOpcional.pas',
  APIRPCheff.DAO.VendaItemOpcional in 'Source\Model\DAO\APIRPCheff.DAO.VendaItemOpcional.pas',
  APIRPCheff.Service.Mesa.Transferencia in 'Source\Model\Service\Mesa\Transferencia\APIRPCheff.Service.Mesa.Transferencia.pas',
  APIRPCheff.Service.Venda.CancelarItem in 'Source\Model\Service\Venda\CancelarItem\APIRPCheff.Service.Venda.CancelarItem.pas',
  APIRPCheff.Service.Mesa.Consulta in 'Source\Model\Service\Mesa\Consulta\APIRPCheff.Service.Mesa.Consulta.pas',
  APIRPCheff.Entity.Configuracao in 'Source\Model\Entity\APIRPCheff.Entity.Configuracao.pas',
  APIRPCheff.DAO.ConfiguracaoMesa in 'Source\Model\DAO\APIRPCheff.DAO.ConfiguracaoMesa.pas',
  APIRPCheff.Service.Venda.Consulta in 'Source\Model\Service\Venda\Consulta\APIRPCheff.Service.Venda.Consulta.pas',
  APIRPCheff.DAO.ConfiguracaoComanda in 'Source\Model\DAO\APIRPCheff.DAO.ConfiguracaoComanda.pas',
  APIRPCheff.Entity.VendaPagamentoAntecipado in 'Source\Model\Entity\APIRPCheff.Entity.VendaPagamentoAntecipado.pas',
  APIRPCheff.DAO.VendaPagamentoAntecipado in 'Source\Model\DAO\APIRPCheff.DAO.VendaPagamentoAntecipado.pas',
  APIRPCheff.Service.Venda.Fechamento in 'Source\Model\Service\Venda\Fechamento\APIRPCheff.Service.Venda.Fechamento.pas',
  APIRPCheff.Entity.EncerraVenda in 'Source\Model\Entity\APIRPCheff.Entity.EncerraVenda.pas',
  APIRPCheff.DAO.EncerraVenda in 'Source\Model\DAO\APIRPCheff.DAO.EncerraVenda.pas',
  APIRPCheff.Entity.EncerraVendaItem in 'Source\Model\Entity\APIRPCheff.Entity.EncerraVendaItem.pas',
  APIRPCheff.DAO.EncerraVendaItem in 'Source\Model\DAO\APIRPCheff.DAO.EncerraVendaItem.pas',
  APIRPCheff.Entity.CaixaItem in 'Source\Model\Entity\APIRPCheff.Entity.CaixaItem.pas',
  APIRPCheff.DAO.CaixaItem in 'Source\Model\DAO\APIRPCheff.DAO.CaixaItem.pas',
  APIRPCheff.Entity.TipoMovimento in 'Source\Model\Entity\APIRPCheff.Entity.TipoMovimento.pas',
  APIRPCheff.DAO.TipoMovimento in 'Source\Model\DAO\APIRPCheff.DAO.TipoMovimento.pas',
  APIRPCheff.Service.Venda.Fechamento.Command in 'Source\Model\Service\Venda\Fechamento\Command\APIRPCheff.Service.Venda.Fechamento.Command.pas',
  APIRPCheff.Service.Venda.Fechamento.Command.AtualizarCouvert in 'Source\Model\Service\Venda\Fechamento\Command\APIRPCheff.Service.Venda.Fechamento.Command.AtualizarCouvert.pas',
  APIRPCheff.Service.Venda.Fechamento.Command.InserirEncerraVenda in 'Source\Model\Service\Venda\Fechamento\Command\APIRPCheff.Service.Venda.Fechamento.Command.InserirEncerraVenda.pas',
  APIRPCheff.Service.Venda.Fechamento.Command.AtualizaCupom in 'Source\Model\Service\Venda\Fechamento\Command\APIRPCheff.Service.Venda.Fechamento.Command.AtualizaCupom.pas',
  APIRPCheff.Service.Venda.Fechamento.Command.SalvarPagamentos in 'Source\Model\Service\Venda\Fechamento\Command\APIRPCheff.Service.Venda.Fechamento.Command.SalvarPagamentos.pas',
  APIRPCheff.Service.Venda.Fechamento.Command.AtualizarItens in 'Source\Model\Service\Venda\Fechamento\Command\APIRPCheff.Service.Venda.Fechamento.Command.AtualizarItens.pas',
  APIRPCheff.Entity.MovimentoEstoque in 'Source\Model\Entity\APIRPCheff.Entity.MovimentoEstoque.pas',
  APIRPCheff.DAO.MovimentoEstoque in 'Source\Model\DAO\APIRPCheff.DAO.MovimentoEstoque.pas',
  APIRPCheff.Service.Venda.Fechamento.Command.AtualizarSetorEstoque in 'Source\Model\Service\Venda\Fechamento\Command\APIRPCheff.Service.Venda.Fechamento.Command.AtualizarSetorEstoque.pas',
  APIRPCheff.Entity.SetorEstoqueMaterial in 'Source\Model\Entity\APIRPCheff.Entity.SetorEstoqueMaterial.pas',
  APIRPCheff.DAO.SetorEstoqueMaterial in 'Source\Model\DAO\APIRPCheff.DAO.SetorEstoqueMaterial.pas',
  APIRPCheff.Service.Venda.Fechamento.Command.InserirMovimentoEstoque in 'Source\Model\Service\Venda\Fechamento\Command\APIRPCheff.Service.Venda.Fechamento.Command.InserirMovimentoEstoque.pas',
  APIRPCheff.Entity.MovimentoEstoqueComposicao in 'Source\Model\Entity\APIRPCheff.Entity.MovimentoEstoqueComposicao.pas',
  APIRPCheff.DAO.MovimentoEstoqueComposicao in 'Source\Model\DAO\APIRPCheff.DAO.MovimentoEstoqueComposicao.pas',
  APIRPCheff.Entity.MateriaisComposicao in 'Source\Model\Entity\APIRPCheff.Entity.MateriaisComposicao.pas',
  APIRPCheff.Entity.Composicao in 'Source\Model\Entity\APIRPCheff.Entity.Composicao.pas',
  APIRPCheff.DAO.MateriaisComposicao in 'Source\Model\DAO\APIRPCheff.DAO.MateriaisComposicao.pas',
  APIRPCheff.Service.Venda.Fechamento.Command.MovimentaComposicao in 'Source\Model\Service\Venda\Fechamento\Command\APIRPCheff.Service.Venda.Fechamento.Command.MovimentaComposicao.pas',
  APIRPCheff.Entity.SetorEstoqueComposicao in 'Source\Model\Entity\APIRPCheff.Entity.SetorEstoqueComposicao.pas',
  APIRPCheff.DAO.SetorEstoqueComposicao in 'Source\Model\DAO\APIRPCheff.DAO.SetorEstoqueComposicao.pas',
  APIRPCheff.Service.Venda.Fechamento.Command.FinalizarVenda in 'Source\Model\Service\Venda\Fechamento\Command\APIRPCheff.Service.Venda.Fechamento.Command.FinalizarVenda.pas',
  APIRPCheff.Controller.VendaItem in 'Source\Controller\APIRPCheff.Controller.VendaItem.pas',
  APIRPCheff.Service.Venda.Fechamento.Command.ValidarFechamento in 'Source\Model\Service\Venda\Fechamento\Command\APIRPCheff.Service.Venda.Fechamento.Command.ValidarFechamento.pas',
  APIRPCheff.Service.Venda.LancarItem.Fracionado in 'Source\Model\Service\Venda\LancarItem\APIRPCheff.Service.Venda.LancarItem.Fracionado.pas',
  APIRPCheff.Service.Venda.LancarItem in 'Source\Model\Service\Venda\LancarItem\APIRPCheff.Service.Venda.LancarItem.pas',
  APIRPCheff.Utils in 'Source\Model\Utils\APIRPCheff.Utils.pas',
  APIRPCheff.Service.Venda.Impressao in 'Source\Model\Service\Venda\Impressao\APIRPCheff.Service.Venda.Impressao.pas',
  APIRPCheff.Service.Venda.Impressao32Colunas in 'Source\Model\Service\Venda\Impressao\APIRPCheff.Service.Venda.Impressao32Colunas.pas',
  APIRPCheff.Service.Venda.Impressao48Colunas in 'Source\Model\Service\Venda\Impressao\APIRPCheff.Service.Venda.Impressao48Colunas.pas',
  APIRPCheff.Service.Venda.Impressao42Colunas in 'Source\Model\Service\Venda\Impressao\APIRPCheff.Service.Venda.Impressao42Colunas.pas',
  APIRPCheff.Entity.Comanda in 'Source\Model\Entity\APIRPCheff.Entity.Comanda.pas',
  APIRPCheff.DAO.Comanda in 'Source\Model\DAO\APIRPCheff.DAO.Comanda.pas',
  APIRPCheff.Service.Comanda.Consulta in 'Source\Model\Service\Comanda\Consulta\APIRPCheff.Service.Comanda.Consulta.pas',
  APIRPCheff.Controller.Comanda in 'Source\Controller\APIRPCheff.Controller.Comanda.pas',
  APIRPCheff.Service.Comanda.Abertura in 'Source\Model\Service\Comanda\Abertura\APIRPCheff.Service.Comanda.Abertura.pas',
  APIRPCheff.Service.Comanda.Transferencia in 'Source\Model\Service\Comanda\Transferencia\APIRPCheff.Service.Comanda.Transferencia.pas',
  APIRPCheff.Entity.Cliente in 'Source\Model\Entity\APIRPCheff.Entity.Cliente.pas',
  APIRPCheff.Entity.CatracaMobile in 'Source\Model\Entity\APIRPCheff.Entity.CatracaMobile.pas',
  APIRPCheff.DAO.CatracaMobile in 'Source\Model\DAO\APIRPCheff.DAO.CatracaMobile.pas',
  APIRPCheff.Entity.VendaPrePago in 'Source\Model\Entity\APIRPCheff.Entity.VendaPrePago.pas',
  APIRPCheff.DAO.VendaPrePago in 'Source\Model\DAO\APIRPCheff.DAO.VendaPrePago.pas',
  APIRPCheff.Service.Venda.Fechamento.Command.SalvarPagamentos.VendaNormal in 'Source\Model\Service\Venda\Fechamento\Command\APIRPCheff.Service.Venda.Fechamento.Command.SalvarPagamentos.VendaNormal.pas',
  APIRPCheff.Service.Venda.Fechamento.Command.SalvarPagamentos.VendaPrePaga in 'Source\Model\Service\Venda\Fechamento\Command\APIRPCheff.Service.Venda.Fechamento.Command.SalvarPagamentos.VendaPrePaga.pas',
  RpError.Exception in 'Source\Error\RpError.Exception.pas',
  RpError.FormError in 'Source\Error\RpError.FormError.pas' {FormError},
  APIRPCheff.Components.Impressora in 'Source\Model\Components\Impressora\APIRPCheff.Components.Impressora.pas',
  APIRPCheff.Service.Venda.LancarItem.ControleGratis in 'Source\Model\Service\Venda\LancarItem\APIRPCheff.Service.Venda.LancarItem.ControleGratis.pas',
  APIRPCheff.Entity.ImpressaoProducao in 'Source\Model\Entity\APIRPCheff.Entity.ImpressaoProducao.pas',
  APIRPCheff.DAO.ImpressaoProducao in 'Source\Model\DAO\APIRPCheff.DAO.ImpressaoProducao.pas',
  APIRPCheff.Entity.Exceptions in 'Source\Model\Entity\APIRPCheff.Entity.Exceptions.pas',
  APIRPCheff.Entity.CancelamentoPagamentoStone in 'Source\Model\Entity\APIRPCheff.Entity.CancelamentoPagamentoStone.pas',
  APIRPCheff.DAO.CancelamentoPagamentoStone in 'Source\Model\DAO\APIRPCheff.DAO.CancelamentoPagamentoStone.pas',
  APIRPCheff.Entity.PagamentoStonePOS in 'Source\Model\Entity\APIRPCheff.Entity.PagamentoStonePOS.pas',
  APIRPCheff.DAO.PagamentoStonePOS in 'Source\Model\DAO\APIRPCheff.DAO.PagamentoStonePOS.pas',
  APIRPCheff.Service.Venda.ImpressaoSTONE in 'Source\Model\Service\Venda\Impressao\APIRPCheff.Service.Venda.ImpressaoSTONE.pas',
  APIRPCheff.Service.Venda.Fechamento.Command.GravarImpressao in 'Source\Model\Service\Venda\Fechamento\Command\APIRPCheff.Service.Venda.Fechamento.Command.GravarImpressao.pas',
  APIRPCheff.Service.Venda.Fechamento.Command.EmitirNota in 'Source\Model\Service\Venda\Fechamento\Command\APIRPCheff.Service.Venda.Fechamento.Command.EmitirNota.pas',
  APIRPCheff.Service.Venda.PreFechamento in 'Source\Model\Service\Venda\PreFechamento\APIRPCheff.Service.Venda.PreFechamento.pas',
  APIRPCheff.Entity.MovimentoEstoqueOpcional in 'Source\Model\Entity\APIRPCheff.Entity.MovimentoEstoqueOpcional.pas',
  APIRPCheff.DAO.MovimentoEstoqueOpcional in 'Source\Model\DAO\APIRPCheff.DAO.MovimentoEstoqueOpcional.pas',
  APIRPCheff.Service.Venda.Fechamento.Command.InserirMovimentoEstoqueOpcional in 'Source\Model\Service\Venda\Fechamento\Command\APIRPCheff.Service.Venda.Fechamento.Command.InserirMovimentoEstoqueOpcional.pas',
  APIRPCheff.Entity.SetorEstoqueOpcional in 'Source\Model\Entity\APIRPCheff.Entity.SetorEstoqueOpcional.pas',
  APIRPCheff.DAO.SetorEstoqueOpcional in 'Source\Model\DAO\APIRPCheff.DAO.SetorEstoqueOpcional.pas',
  APIRPCheff.Resources.Configuracao in 'Resources\APIRPCheff.Resources.Configuracao.pas',
  APIRPCheff.Service.Venda.ImpressaoSTONE.NFCe in 'Source\Model\Service\Venda\Impressao\APIRPCheff.Service.Venda.ImpressaoSTONE.NFCe.pas',
  APIRPCheff.Service.Venda.ImpressaoPlugPag in 'Source\Model\Service\Venda\Impressao\APIRPCheff.Service.Venda.ImpressaoPlugPag.pas',
  APIRPCheff.Service.Venda.ImpressaoPlugPag.NFCe in 'Source\Model\Service\Venda\Impressao\APIRPCheff.Service.Venda.ImpressaoPlugPag.NFCe.pas',
  APIRPCheff.Service.Venda.ImpressaoCielo in 'Source\Model\Service\Venda\Impressao\APIRPCheff.Service.Venda.ImpressaoCielo.pas',
  APIRPCheff.Service.Venda.ImpressaoCielo.NFCe in 'Source\Model\Service\Venda\Impressao\APIRPCheff.Service.Venda.ImpressaoCielo.NFCe.pas',
  APIRPCheff.Context.Venda.Fechamento in 'Source\Model\Context\APIRPCheff.Context.Venda.Fechamento.pas',
  APIRPCheff.Service.Venda.Fechamento.Command.ProximoIdCaixaItem in 'Source\Model\Service\Venda\Fechamento\Command\APIRPCheff.Service.Venda.Fechamento.Command.ProximoIdCaixaItem.pas',
  APIRPCheff.Service.Venda.PagamentoParcial in 'Source\Model\Service\Venda\PagamentoParcial\APIRPCheff.Service.Venda.PagamentoParcial.pas',
  APIRPCheff.Service.Venda.PagamentoParcial.Command in 'Source\Model\Service\Venda\PagamentoParcial\Command\APIRPCheff.Service.Venda.PagamentoParcial.Command.pas',
  APIRPCheff.Context.Venda.PagamentoParcial in 'Source\Model\Context\APIRPCheff.Context.Venda.PagamentoParcial.pas',
  APIRPCheff.Service.Venda.PagamentoParcial.Command.ProximoIdCaixaItem in 'Source\Model\Service\Venda\PagamentoParcial\Command\APIRPCheff.Service.Venda.PagamentoParcial.Command.ProximoIdCaixaItem.pas',
  APIRPCheff.Service.Venda.PagamentoParcial.Command.InserirCaixaItem in 'Source\Model\Service\Venda\PagamentoParcial\Command\APIRPCheff.Service.Venda.PagamentoParcial.Command.InserirCaixaItem.pas',
  APIRPCheff.Service.Venda.PagamentoParcial.Command.InserirPagamentoAntecipados in 'Source\Model\Service\Venda\PagamentoParcial\Command\APIRPCheff.Service.Venda.PagamentoParcial.Command.InserirPagamentoAntecipados.pas',
  APIRPCheff.Entity.Venda.PagamentoAntecipadoItens in 'Source\Model\Entity\APIRPCheff.Entity.Venda.PagamentoAntecipadoItens.pas',
  APIRPCheff.DAO.Venda.PagamentoAntecipadoItens in 'Source\Model\DAO\APIRPCheff.DAO.Venda.PagamentoAntecipadoItens.pas',
  APIRPCheff.Service.Venda.PagamentoParcial.Command.InserirPagamentoAntecipadoItens in 'Source\Model\Service\Venda\PagamentoParcial\Command\APIRPCheff.Service.Venda.PagamentoParcial.Command.InserirPagamentoAntecipadoItens.pas',
  APIRPCheff.Service.Mesa.Juncao in 'Source\Model\Service\Mesa\Juncao\APIRPCheff.Service.Mesa.Juncao.pas';

{$R *.res}

begin
  TStyleManager.TrySetStyle('Iceberg Classico');
{$IFDEF DEBUG}
  ReportMemoryLeaksOnShutdown := True;
{$ENDIF}
  CreateServer;

  WinServiceSetup
    .ServiceName('RPCheff')
    .ServiceTitle('RPCheff API')
    .ServiceDetail('API usada pelo aplicativo LeCheff')
    .OnStart(StartServer)
    .OnStop(StopServer);

  if not WinServiceSetup.RunAsService then
    WinServiceSetup.CreateForm(TAPIRPCheffViewPrincipal, APIRPCheffViewPrincipal);
end.
