--
-- PostgreSQL database dump
--

\restrict 6DslDB6Oh2euGB8sEmrlfaJGPwNKhFwJtNDF8JWUGPnaFOrU8Vj7EOkq3ugyjnl

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: is_atendimento_disponivel(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.is_atendimento_disponivel() RETURNS boolean
    LANGUAGE plpgsql
    AS $$
DECLARE
    atendimento_disponivel BOOLEAN := false;
    config configuracao_funcionamento%ROWTYPE;
    current_day_of_week INTEGER;
    current_local_time TIME;
BEGIN
    -- Obter o dia da semana atual (0 para domingo, 1 para segunda-feira, 2 para terça-feira, etc.)
    current_day_of_week := EXTRACT(DOW FROM CURRENT_DATE)::INTEGER;

    -- Obter o horário atual em 'America/Sao_Paulo'
    current_local_time := (SELECT Current_Time at time zone 'America/Sao_Paulo');

    -- Obter as configurações de atendimento
    SELECT * INTO config FROM configuracao_funcionamento LIMIT 1;

    -- Verificar se o atendimento está disponível no dia da semana atual
    CASE current_day_of_week
        WHEN 1 THEN
            atendimento_disponivel := config.dia_segunda AND
                current_local_time >= config.segunda_inicio_atendimento AND
                current_local_time <= config.segunda_fim_atendimento;
        WHEN 2 THEN
            atendimento_disponivel := config.dia_terca AND
                current_local_time >= config.terca_inicio_atendimento AND
                current_local_time <= config.terca_fim_atendimento;
        WHEN 3 THEN
            atendimento_disponivel := config.dia_quarta AND
                current_local_time >= config.quarta_inicio_atendimento AND
                current_local_time <= config.quarta_fim_atendimento;
        WHEN 4 THEN
            atendimento_disponivel := config.dia_quinta AND
                current_local_time >= config.quinta_inicio_atendimento AND
                current_local_time <= config.quinta_fim_atendimento;
        WHEN 5 THEN
            atendimento_disponivel := config.dia_sexta AND
                current_local_time >= config.sexta_inicio_atendimento AND
                current_local_time <= config.sexta_fim_atendimento;
        WHEN 6 THEN
            atendimento_disponivel := config.dia_sabado AND
                current_local_time >= config.sabado_inicio_atendimento AND
                current_local_time <= config.sabado_fim_atendimento;
        WHEN 0 THEN
            atendimento_disponivel := config.dia_domingo AND
                current_local_time >= config.domingo_inicio_atendimento AND
                current_local_time <= config.domingo_fim_atendimento;
    END CASE;

    RETURN atendimento_disponivel;
END;
$$;


ALTER FUNCTION public.is_atendimento_disponivel() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bairro; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bairro (
    bai_001 integer NOT NULL,
    emp_001 integer NOT NULL,
    bai_002 character varying(60) NOT NULL,
    bai_003 numeric(15,2),
    sit_001 integer DEFAULT 4 NOT NULL,
    b_restricao_entrega boolean DEFAULT false NOT NULL
);


ALTER TABLE public.bairro OWNER TO postgres;

--
-- Name: bairro_ceps; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bairro_ceps (
    bai_001 integer NOT NULL,
    emp_001 integer NOT NULL,
    cep character varying(9) NOT NULL,
    logradouro character varying(125),
    id_cidade integer,
    cidade_desc character varying(75),
    uf_sigla character varying(2)
);


ALTER TABLE public.bairro_ceps OWNER TO postgres;

--
-- Name: clientes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.clientes (
    id_empresa integer DEFAULT 1 NOT NULL,
    cli_004 character varying(20),
    sit_001 integer DEFAULT 4 NOT NULL,
    observacao text,
    senha_email character varying(100),
    pontos_atuais integer,
    email character varying(100),
    tipo_pessoa character varying(1) DEFAULT 'F'::character varying,
    celular1 character varying(30),
    cli_001 integer NOT NULL,
    cli_012 character varying(50),
    cli_002 character varying(100)
);


ALTER TABLE public.clientes OWNER TO postgres;

--
-- Name: clientes_cli_001_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.clientes ALTER COLUMN cli_001 ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_cli_001_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clientes_endereco; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.clientes_endereco (
    id_endereco integer NOT NULL,
    cli_001 integer NOT NULL,
    id_empresa integer NOT NULL,
    cep_002 character varying(9),
    cep_003 character varying(50),
    cep_004 character varying(125),
    cli_007 character varying(80),
    cli_008 character varying(100),
    cli_009 character varying(100),
    bai_001 integer,
    endereco_padrao boolean DEFAULT false,
    taxa numeric(15,3),
    idcidade integer,
    uf character varying(50)
);


ALTER TABLE public.clientes_endereco OWNER TO postgres;

--
-- Name: clientes_endereco_id_endereco_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.clientes_endereco ALTER COLUMN id_endereco ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_endereco_id_endereco_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: configuracao_funcionamento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.configuracao_funcionamento (
    dia_segunda boolean DEFAULT false NOT NULL,
    dia_terca boolean DEFAULT false NOT NULL,
    dia_quarta boolean DEFAULT false NOT NULL,
    dia_quinta boolean DEFAULT false NOT NULL,
    dia_sexta boolean DEFAULT false NOT NULL,
    dia_sabado boolean DEFAULT false NOT NULL,
    dia_domingo boolean DEFAULT false NOT NULL,
    segunda_inicio_atendimento time without time zone DEFAULT '00:00:00'::time without time zone NOT NULL,
    terca_inicio_atendimento time without time zone DEFAULT '00:00:00'::time without time zone NOT NULL,
    quarta_inicio_atendimento time without time zone DEFAULT '00:00:00'::time without time zone NOT NULL,
    quinta_inicio_atendimento time without time zone DEFAULT '00:00:00'::time without time zone NOT NULL,
    sexta_inicio_atendimento time without time zone DEFAULT '00:00:00'::time without time zone NOT NULL,
    sabado_inicio_atendimento time without time zone DEFAULT '00:00:00'::time without time zone NOT NULL,
    domingo_inicio_atendimento time without time zone DEFAULT '00:00:00'::time without time zone NOT NULL,
    segunda_fim_atendimento time without time zone DEFAULT '00:00:00'::time without time zone NOT NULL,
    terca_fim_atendimento time without time zone DEFAULT '00:00:00'::time without time zone NOT NULL,
    quarta_fim_atendimento time without time zone DEFAULT '00:00:00'::time without time zone NOT NULL,
    quinta_fim_atendimento time without time zone DEFAULT '00:00:00'::time without time zone NOT NULL,
    sexta_fim_atendimento time without time zone DEFAULT '00:00:00'::time without time zone NOT NULL,
    sabado_fim_atendimento time without time zone DEFAULT '00:00:00'::time without time zone NOT NULL,
    domingo_fim_atendimento time without time zone DEFAULT '00:00:00'::time without time zone NOT NULL,
    id_empresa integer NOT NULL,
    id integer NOT NULL
);


ALTER TABLE public.configuracao_funcionamento OWNER TO postgres;

--
-- Name: configuracao_funcionamento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.configuracao_funcionamento_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.configuracao_funcionamento_id_seq OWNER TO postgres;

--
-- Name: configuracao_funcionamento_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.configuracao_funcionamento_id_seq OWNED BY public.configuracao_funcionamento.id;


--
-- Name: configuracao_rpfood; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.configuracao_rpfood (
    id_empresa integer DEFAULT 1 NOT NULL,
    tempo_retirada_rpfood integer DEFAULT 0 NOT NULL,
    tempo_entrega_rpfood integer DEFAULT 0 NOT NULL,
    utiliza_tipo_entrega_retirada boolean DEFAULT true,
    modo_acougue boolean DEFAULT false NOT NULL,
    pedido_minimo numeric(15,2) DEFAULT 0.00 NOT NULL,
    id integer NOT NULL,
    utiliza_controle_opcionais boolean DEFAULT false,
    utiliza_controle_ceps boolean DEFAULT true
);


ALTER TABLE public.configuracao_rpfood OWNER TO postgres;

--
-- Name: configuracao_rpfood_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.configuracao_rpfood_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.configuracao_rpfood_id_seq OWNER TO postgres;

--
-- Name: configuracao_rpfood_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.configuracao_rpfood_id_seq OWNED BY public.configuracao_rpfood.id;


--
-- Name: empresas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.empresas (
    descricao character varying(40),
    codiuf integer,
    codicidade integer,
    uf character varying(2),
    cidade character varying(30),
    bairro character varying(30),
    endereco character varying(60),
    tipoendereco character varying(30),
    nome character varying(60),
    razsoc character varying(60),
    cnpj character varying(18),
    cep character varying(20),
    numero character varying(20),
    fone1 character varying(30),
    descrifone1 character varying(20),
    ddd1 character(3),
    email character varying(100),
    site character varying(100),
    complemento character varying(100),
    id_situacao integer DEFAULT 4 NOT NULL,
    inscricao_estadual character varying(18),
    id_empresa integer NOT NULL
);


ALTER TABLE public.empresas OWNER TO postgres;

--
-- Name: empresas_id_empresa_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.empresas ALTER COLUMN id_empresa ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.empresas_id_empresa_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: formapgto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formapgto (
    id integer NOT NULL,
    id_empresa integer NOT NULL,
    descricao character varying(50),
    id_situacao integer,
    b_venda_web boolean DEFAULT false,
    sfi_codigo integer
);


ALTER TABLE public.formapgto OWNER TO postgres;

--
-- Name: grupos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.grupos (
    codigo integer NOT NULL,
    descricao character varying(60),
    img bytea,
    id_situacao integer DEFAULT 4 NOT NULL,
    id_empresa integer NOT NULL,
    b_exibir_web boolean DEFAULT false NOT NULL
);


ALTER TABLE public.grupos OWNER TO postgres;

--
-- Name: happy_hour; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.happy_hour (
    id integer NOT NULL,
    idproduto integer NOT NULL,
    idempresa integer NOT NULL,
    horainicial time without time zone NOT NULL,
    horafinal time without time zone NOT NULL,
    segundafeira boolean NOT NULL,
    tercafeira boolean NOT NULL,
    quartafeira boolean NOT NULL,
    quintafeira boolean NOT NULL,
    sextafeira boolean NOT NULL,
    sabado boolean NOT NULL,
    domingo boolean NOT NULL,
    valor numeric(15,3) NOT NULL,
    utiliza_mesa boolean DEFAULT false,
    utiliza_delivery boolean DEFAULT false
);


ALTER TABLE public.happy_hour OWNER TO postgres;

--
-- Name: happy_hour_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.happy_hour_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.happy_hour_id_seq OWNER TO postgres;

--
-- Name: happy_hour_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.happy_hour_id_seq OWNED BY public.happy_hour.id;


--
-- Name: mesa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mesa (
    mes_001 integer,
    emp_001 integer,
    mes_002 character varying(30),
    mes_003 integer,
    id_situacao integer DEFAULT 4
);


ALTER TABLE public.mesa OWNER TO postgres;

--
-- Name: opcional; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.opcional (
    codigo integer NOT NULL,
    id_empresa integer NOT NULL,
    descricao character varying(100) NOT NULL,
    valor numeric(15,2) NOT NULL,
    id_situacao integer DEFAULT 4 NOT NULL,
    opc_p character varying(100),
    opc_m character varying(100),
    opc_g character varying(100),
    opc_extra character varying(100),
    valor_opc_p numeric(15,2) DEFAULT 0.00,
    valor_opc_g numeric(15,2) DEFAULT 0.00,
    valor_opc_m numeric(15,2) DEFAULT 0.00,
    valor_opc_gg numeric(15,2) DEFAULT 0.00,
    valor_opc_extra numeric(15,2) DEFAULT 0.00,
    tipo integer DEFAULT 0 NOT NULL,
    opc_gg character varying(100),
    imagem_db bytea
);


ALTER TABLE public.opcional OWNER TO postgres;

--
-- Name: produtos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.produtos (
    codigo integer NOT NULL,
    descricao character varying(60),
    codigrupo integer,
    valfinal numeric(15,2),
    valcompra numeric(15,2),
    observacao character varying(1200),
    img1 bytea,
    img2 bytea,
    img bytea,
    id_situacao integer DEFAULT 4 NOT NULL,
    id_empresa integer NOT NULL,
    b_venda_web boolean DEFAULT false NOT NULL,
    utiliza_combo boolean DEFAULT false NOT NULL,
    b_destaque_web boolean DEFAULT false,
    b_permite_frac boolean DEFAULT true NOT NULL,
    tamanho_p character varying(100),
    tamanho_m character varying(100),
    tamanho_g character varying(100),
    tamanho_gg character varying(100),
    tamanho_extra character varying(100),
    tamanho_padrao character varying(2) DEFAULT 'M'::character varying,
    valor_tam_p numeric(15,2) DEFAULT 0.00,
    valor_tam_m numeric(15,2) DEFAULT 0.00,
    valor_tam_g numeric(15,2) DEFAULT 0.00,
    valor_tam_gg numeric(15,2) DEFAULT 0.00,
    b_venda_tamanho boolean DEFAULT false,
    valor_tam_extra numeric(15,2) DEFAULT 0.00,
    b_carrossel boolean DEFAULT false,
    utiliza_promocao boolean DEFAULT false,
    b_exporta_peso_balanca boolean DEFAULT false,
    b_peso_balanca boolean DEFAULT false NOT NULL,
    restringirvenda boolean DEFAULT false,
    utiliza_happy_hour boolean DEFAULT false,
    opcional_minimo integer DEFAULT 0,
    opcional_maximo integer DEFAULT 0
);


ALTER TABLE public.produtos OWNER TO postgres;

--
-- Name: produtos_opcional; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.produtos_opcional (
    id_empresa integer NOT NULL,
    id_material integer NOT NULL,
    id_opcional integer NOT NULL
);


ALTER TABLE public.produtos_opcional OWNER TO postgres;

--
-- Name: promocao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.promocao (
    id_promocao integer NOT NULL,
    id_empresa integer NOT NULL,
    id_material integer NOT NULL,
    tipo_desconto integer DEFAULT 0 NOT NULL,
    segundafeira boolean DEFAULT false NOT NULL,
    tercafeira boolean DEFAULT false NOT NULL,
    quartafeira boolean DEFAULT false NOT NULL,
    quintafeira boolean DEFAULT false NOT NULL,
    sextafeira boolean DEFAULT false NOT NULL,
    sabado boolean DEFAULT false NOT NULL,
    domingo boolean DEFAULT false NOT NULL,
    tipomesa boolean DEFAULT false NOT NULL,
    tipodelivery boolean DEFAULT false NOT NULL,
    tipocomanda boolean DEFAULT false NOT NULL,
    descontosegundapadrao numeric(15,3) DEFAULT 0,
    descontosegundatamanhop numeric(15,3) DEFAULT 0,
    descontosegundatamanhom numeric(15,3) DEFAULT 0,
    descontosegundatamanhog numeric(15,3) DEFAULT 0,
    descontosegundatamanhogg numeric(15,3) DEFAULT 0,
    descontosegundatamanhoextra numeric(15,3) DEFAULT 0,
    desconto_ter_padrao numeric(15,3) DEFAULT 0,
    desconto_ter_tam_p numeric(15,3) DEFAULT 0,
    desconto_ter_tam_m numeric(15,3) DEFAULT 0,
    desconto_ter_tam_g numeric(15,3) DEFAULT 0,
    desconto_ter_tam_gg numeric(15,3) DEFAULT 0,
    desconto_ter_tam_extra numeric(15,3) DEFAULT 0,
    desconto_qua_padrao numeric(15,3) DEFAULT 0,
    desconto_qua_tam_p numeric(15,3) DEFAULT 0,
    desconto_qua_tam_m numeric(15,3) DEFAULT 0,
    desconto_qua_tam_g numeric(15,3) DEFAULT 0,
    desconto_qua_tam_gg numeric(15,3) DEFAULT 0,
    desconto_qua_tam_extra numeric(15,3) DEFAULT 0,
    desconto_qui_padrao numeric(15,3) DEFAULT 0,
    desconto_qui_tam_p numeric(15,3) DEFAULT 0,
    desconto_qui_tam_m numeric(15,3) DEFAULT 0,
    desconto_qui_tam_g numeric(15,3) DEFAULT 0,
    desconto_qui_tam_gg numeric(15,3) DEFAULT 0,
    desconto_qui_tam_extra numeric(15,3) DEFAULT 0,
    desconto_sex_padrao numeric(15,3) DEFAULT 0,
    desconto_sex_tam_p numeric(15,3) DEFAULT 0,
    desconto_sex_tam_m numeric(15,3) DEFAULT 0,
    desconto_sex_tam_g numeric(15,3) DEFAULT 0,
    desconto_sex_tam_gg numeric(15,3) DEFAULT 0,
    desconto_sex_tam_extra numeric(15,3) DEFAULT 0,
    desconto_sab_padrao numeric(15,3) DEFAULT 0,
    desconto_sab_tam_p numeric(15,3) DEFAULT 0,
    desconto_sab_tam_m numeric(15,3) DEFAULT 0,
    desconto_sab_tam_g numeric(15,3) DEFAULT 0,
    desconto_sab_tam_gg numeric(15,3) DEFAULT 0,
    desconto_sab_tam_extra numeric(15,3) DEFAULT 0,
    desconto_dom_padrao numeric(15,3) DEFAULT 0,
    desconto_dom_tam_p numeric(15,3) DEFAULT 0,
    desconto_dom_tam_m numeric(15,3) DEFAULT 0,
    desconto_dom_tam_g numeric(15,3) DEFAULT 0,
    desconto_dom_tam_gg numeric(15,3) DEFAULT 0,
    desconto_dom_tam_extra numeric(15,3) DEFAULT 0
);


ALTER TABLE public.promocao OWNER TO postgres;

--
-- Name: restricoesvendas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restricoesvendas (
    idempresa integer,
    idproduto integer,
    segundafeira boolean DEFAULT false,
    tercafeira boolean DEFAULT false,
    quartafeira boolean DEFAULT false,
    quintafeira boolean DEFAULT false,
    sextafeira boolean DEFAULT false,
    sabado boolean DEFAULT false,
    domingo boolean DEFAULT false
);


ALTER TABLE public.restricoesvendas OWNER TO postgres;

--
-- Name: sincronizacao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sincronizacao (
    id integer NOT NULL,
    data timestamp without time zone NOT NULL,
    id_empresa integer NOT NULL
);


ALTER TABLE public.sincronizacao OWNER TO postgres;

--
-- Name: COLUMN sincronizacao.id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.sincronizacao.id IS 'ID de sincronizacao';


--
-- Name: COLUMN sincronizacao.data; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.sincronizacao.data IS 'Data da sincronizacao';


--
-- Name: COLUMN sincronizacao.id_empresa; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.sincronizacao.id_empresa IS 'ID da empresa';


--
-- Name: transferencia_imagens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transferencia_imagens (
    id integer NOT NULL,
    tipo character varying(10) NOT NULL,
    id_empresa integer DEFAULT 1 NOT NULL,
    id_registro integer NOT NULL
);


ALTER TABLE public.transferencia_imagens OWNER TO postgres;

--
-- Name: transferencia_imagens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.transferencia_imagens_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.transferencia_imagens_id_seq OWNER TO postgres;

--
-- Name: transferencia_imagens_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.transferencia_imagens_id_seq OWNED BY public.transferencia_imagens.id;


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    codigo integer NOT NULL,
    nome character varying(30),
    senha character varying(60),
    email character varying(100),
    id_situacao integer DEFAULT 4 NOT NULL
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- Name: usuarios_empresa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios_empresa (
    codigo_usuario integer NOT NULL,
    id_empresa integer NOT NULL
);


ALTER TABLE public.usuarios_empresa OWNER TO postgres;

--
-- Name: usuarios_permissoes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios_permissoes (
    codigo_usuario integer NOT NULL,
    b_acesso_web boolean DEFAULT false,
    b_admin_web boolean DEFAULT false,
    id_empresa integer DEFAULT 1 NOT NULL
);


ALTER TABLE public.usuarios_permissoes OWNER TO postgres;

--
-- Name: venda; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.venda (
    id_venda integer NOT NULL,
    id_empresa integer NOT NULL,
    id_situacao integer NOT NULL,
    id_formapgto integer NOT NULL,
    id_cliente integer NOT NULL,
    totals_products numeric(15,2),
    sub_total numeric(15,2),
    taxa_entrega numeric(15,2),
    troco numeric(15,2),
    valor_receber numeric(15,2),
    sales numeric(15,2),
    data_pedido timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    b_recebido_lecheff boolean DEFAULT false NOT NULL,
    tipo_entrega character varying(2) DEFAULT 'D'::character varying NOT NULL,
    observacao character varying(200)
);


ALTER TABLE public.venda OWNER TO postgres;

--
-- Name: venda_endereco; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.venda_endereco (
    id_venda integer NOT NULL,
    id_cliente integer NOT NULL,
    id_bairro integer,
    cep character varying(14) NOT NULL,
    logradouro character varying(150) NOT NULL,
    numero character varying(30),
    complemento character varying(150),
    ponto_referencia character varying(150),
    bairro_desc character varying(100),
    id_endereco integer
);


ALTER TABLE public.venda_endereco OWNER TO postgres;

--
-- Name: venda_id_venda_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.venda ALTER COLUMN id_venda ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.venda_id_venda_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vendaitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vendaitem (
    id_venda integer NOT NULL,
    id_empresa integer NOT NULL,
    id_product integer NOT NULL,
    numero_item integer NOT NULL,
    quantidade numeric(15,4) DEFAULT 0 NOT NULL,
    valor_unit_product numeric(15,4) DEFAULT 0 NOT NULL,
    totals_products numeric(15,4) DEFAULT 0 NOT NULL,
    id_situacao integer,
    tamanho character varying(40),
    b_venda_tamanho boolean DEFAULT false,
    item_fracionado integer,
    observacao character varying(150),
    utilizou_happy_hour boolean DEFAULT false
);


ALTER TABLE public.vendaitem OWNER TO postgres;

--
-- Name: vendaitemopcional; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vendaitemopcional (
    id_venda integer NOT NULL,
    id_empresa integer NOT NULL,
    id_numero_item integer NOT NULL,
    id_opcional integer NOT NULL,
    gratis numeric(15,4) DEFAULT 0 NOT NULL,
    valor numeric(15,4) DEFAULT 0 NOT NULL,
    valorunitario numeric(15,4) DEFAULT 0 NOT NULL,
    valortotal numeric(15,4) DEFAULT 0 NOT NULL,
    quantidade numeric(15,4) DEFAULT 0 NOT NULL,
    quantidade_replicar numeric(15,4) DEFAULT 0 NOT NULL,
    b_recebido_lecheff boolean DEFAULT false
);


ALTER TABLE public.vendaitemopcional OWNER TO postgres;

--
-- Name: vendamesa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vendamesa (
    id_venda integer,
    id_empresa integer,
    id_situacao integer,
    totals_products numeric(15,3),
    sub_total numeric(15,3),
    sales numeric(15,3),
    data_pedido timestamp without time zone,
    b_recebido_lecheff boolean DEFAULT false,
    observacao character varying(300),
    numero_mesa integer,
    descricao_mesa character varying(20)
);


ALTER TABLE public.vendamesa OWNER TO postgres;

--
-- Name: vendamesaitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vendamesaitem (
    id_venda integer NOT NULL,
    id_empresa integer NOT NULL,
    id_product integer NOT NULL,
    numero_item integer NOT NULL,
    quantidade numeric(15,4) DEFAULT 0 NOT NULL,
    valor_unit_product numeric(15,4) DEFAULT 0 NOT NULL,
    totals_products numeric(15,4) DEFAULT 0 NOT NULL,
    id_situacao integer,
    tamanho character varying(2),
    b_venda_tamanho boolean DEFAULT false,
    item_fracionado integer,
    observacao character varying(150),
    b_recebido_lecheff boolean DEFAULT false,
    utilizou_happy_hour boolean DEFAULT false,
    utilizou_promocao boolean DEFAULT false
);


ALTER TABLE public.vendamesaitem OWNER TO postgres;

--
-- Name: vendas_status_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vendas_status_log (
    id_venda integer NOT NULL,
    id_empresa integer DEFAULT 1 NOT NULL,
    id_situacao integer NOT NULL,
    data timestamp without time zone
);


ALTER TABLE public.vendas_status_log OWNER TO postgres;

--
-- Name: configuracao_funcionamento id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.configuracao_funcionamento ALTER COLUMN id SET DEFAULT nextval('public.configuracao_funcionamento_id_seq'::regclass);


--
-- Name: configuracao_rpfood id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.configuracao_rpfood ALTER COLUMN id SET DEFAULT nextval('public.configuracao_rpfood_id_seq'::regclass);


--
-- Name: happy_hour id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.happy_hour ALTER COLUMN id SET DEFAULT nextval('public.happy_hour_id_seq'::regclass);


--
-- Name: transferencia_imagens id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transferencia_imagens ALTER COLUMN id SET DEFAULT nextval('public.transferencia_imagens_id_seq'::regclass);


--
-- Name: configuracao_funcionamento configuracao_funcionamento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.configuracao_funcionamento
    ADD CONSTRAINT configuracao_funcionamento_pkey PRIMARY KEY (id);


--
-- Name: configuracao_rpfood configuracao_rpfood_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.configuracao_rpfood
    ADD CONSTRAINT configuracao_rpfood_pkey PRIMARY KEY (id);


--
-- Name: empresas empresas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empresas
    ADD CONSTRAINT empresas_pkey PRIMARY KEY (id_empresa);


--
-- Name: formapgto formapgto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formapgto
    ADD CONSTRAINT formapgto_pkey PRIMARY KEY (id, id_empresa);


--
-- Name: grupos grupos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grupos
    ADD CONSTRAINT grupos_pkey PRIMARY KEY (codigo, id_empresa);


--
-- Name: happy_hour happy_hour_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.happy_hour
    ADD CONSTRAINT happy_hour_pkey PRIMARY KEY (id);


--
-- Name: opcional opcional_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.opcional
    ADD CONSTRAINT opcional_pkey PRIMARY KEY (codigo, id_empresa);


--
-- Name: bairro pk_bairro; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bairro
    ADD CONSTRAINT pk_bairro PRIMARY KEY (bai_001, emp_001);


--
-- Name: bairro_ceps pk_bairro_ceps; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bairro_ceps
    ADD CONSTRAINT pk_bairro_ceps PRIMARY KEY (bai_001, emp_001, cep);


--
-- Name: clientes_endereco pk_clientes_endereco; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clientes_endereco
    ADD CONSTRAINT pk_clientes_endereco PRIMARY KEY (id_endereco, id_empresa);


--
-- Name: promocao pk_promocao; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.promocao
    ADD CONSTRAINT pk_promocao PRIMARY KEY (id_promocao, id_empresa);


--
-- Name: usuarios pk_usuarios; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT pk_usuarios PRIMARY KEY (codigo);


--
-- Name: usuarios_empresa pk_usuarios_empresa; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios_empresa
    ADD CONSTRAINT pk_usuarios_empresa PRIMARY KEY (codigo_usuario, id_empresa);


--
-- Name: venda pk_venda; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venda
    ADD CONSTRAINT pk_venda PRIMARY KEY (id_venda, id_empresa);


--
-- Name: vendaitem pk_vendaitem; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vendaitem
    ADD CONSTRAINT pk_vendaitem PRIMARY KEY (id_venda, id_empresa, numero_item);


--
-- Name: vendamesaitem pk_vendamesaitem; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vendamesaitem
    ADD CONSTRAINT pk_vendamesaitem PRIMARY KEY (id_venda, id_empresa, numero_item);


--
-- Name: produtos produtos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produtos
    ADD CONSTRAINT produtos_pkey PRIMARY KEY (codigo, id_empresa);


--
-- Name: venda_endereco venda_endereco_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venda_endereco
    ADD CONSTRAINT venda_endereco_pkey PRIMARY KEY (id_venda, id_cliente);


--
-- Name: bairro_ceps fk_bairro_ceps; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bairro_ceps
    ADD CONSTRAINT fk_bairro_ceps FOREIGN KEY (bai_001, emp_001) REFERENCES public.bairro(bai_001, emp_001) ON DELETE CASCADE;


--
-- Name: formapgto fk_formapgto_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formapgto
    ADD CONSTRAINT fk_formapgto_id FOREIGN KEY (id_empresa) REFERENCES public.empresas(id_empresa) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: promocao fk_promocao_idmaterial; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.promocao
    ADD CONSTRAINT fk_promocao_idmaterial FOREIGN KEY (id_material, id_empresa) REFERENCES public.produtos(codigo, id_empresa) ON DELETE CASCADE;


--
-- Name: vendaitem fk_venda_item_empresa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vendaitem
    ADD CONSTRAINT fk_venda_item_empresa FOREIGN KEY (id_empresa) REFERENCES public.empresas(id_empresa) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 6DslDB6Oh2euGB8sEmrlfaJGPwNKhFwJtNDF8JWUGPnaFOrU8Vj7EOkq3ugyjnl

